spring:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5433/corsiDB
    username: postgres
    password: Argolone92!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

# CONFIGURAZIONE SECONDO DATASOURCE
auth:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5433/securitydb  # Modificato da 'url' a 'jdbcUrl'
    username: postgres
    password: Argolone92!
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

discenti:
  service:
    url: http://localhost:8080
docenti:
  service:
    url: http://localhost:8080