spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/scuola
    username: postgres
    password: Argolone92!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

docenti:
  service:
    url: http://localhost:8080
